In [1]:
import tensorflow as tf

print(tf.__version__)

2.17.0


In [2]:
# Create a Scaler

scaler = tf.constant(10)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [13]:
scaler.ndim

# As Scaler is a constant ---> its dimension is zero.

1

In [4]:
scaler = tf.constant([10,20,30])
scaler

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

In [5]:
scaler.ndim

1

In [6]:
matrix = tf.constant([[10,7],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# IF YOU WANT TO PASS AS THE FLOAT
matrix = tf.constant([[10,7],[3,4]],dtype=tf.float16)
matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  4.]], dtype=float16)>

In [10]:
matrix[0] = [2,2]
matrix


# AS THE MATRIX IS CONSTANT, WE CANNOT CHANGE IT

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [11]:
matrix2 = tf.Variable([[10,7],[3,4]])
matrix2[0].assign([1,2])

matrix2

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [14]:
# GENERATING RANDOM NUMBERS USING TENSORFLOW

tf.random.normal(shape=(3,2))

# AS THE NORMAL DISTRIUBTION RANGES FROM [-3,+3] INCLUDING FLOATING VALUES

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.3859527 , -0.3744491 ],
       [ 1.4225467 , -0.8621707 ],
       [ 0.4735918 , -0.19168313]], dtype=float32)>

In [16]:
tf.random.uniform(shape=(3,2))

# AS THE UNIFORM DISTRIBUTION RANGES FROM [0,+1] INCLUDING FLOATING VALUES

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.6996497 , 0.6561593 ],
       [0.5387399 , 0.92301106],
       [0.5993911 , 0.08881342]], dtype=float32)>

In [20]:
# IF WE WANT TO FIX AFTER RUNNING SO MANY TIMES ALSO VALUES DOESN'T CHANGES

r1 = tf.random.Generator.from_seed(42)
r1.uniform(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [21]:
# GIVES ONLY ONE VALUES

tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [22]:
# GIVES ONLY ZEROS

tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [26]:
import numpy as np
t1 = np.arange(1,25)
t1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [25]:
# CHANGING SHAPE OF DATA

tf.constant(t1,shape=(2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>