In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input

In [9]:
# EXAMPLE LABELS --> MULTI CLASS -> USE SOFT MAX
labels = np.array([0,1,2,1,0])

# FEATURES(FOR SIMPLICITY, CREATE SOME DUMMY FEATURES)
features = np.array([
    [1,2],
    [2,3],
    [3,4],
    [4,5],
    [5,6]
])


# ONE HOT ENCODING THE LABELS
one_hot_encoder = OneHotEncoder(sparse_output=False)
labels_one_hot = one_hot_encoder.fit_transform(labels.reshape(-1,1))

X = features
Y = labels_one_hot

In [10]:
Y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [11]:
# BUILDING THE ANN MODEL

model = Sequential()
model.add(Input(shape=(2,)))  # INPUT LAYER
model.add(Dense(4,activation='relu'))  # HIDDEN LAYER
model.add(Dense(3,activation='softmax')) # OUTPUT LAYER WITH 3 CLASSES

In [12]:
# COMPILE THE MODEL WITH SPARSE CATEGORICAL CROSS-ENTROPY
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [14]:
# TRAINING THE MODEL
model.fit(X , Y , epochs = 50 , batch_size = 1 , verbose = 1)

Epoch 1/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.2306 - loss: 1.1135      
Epoch 2/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3556 - loss: 1.1100     
Epoch 3/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6611 - loss: 1.0965 
Epoch 4/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4111 - loss: 1.1070     
Epoch 5/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5222 - loss: 1.1016 
Epoch 6/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3556 - loss: 1.0997     
Epoch 7/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2306 - loss: 1.1000     
Epoch 8/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8250 - loss: 1.0958 
Epoch 9/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5778 - loss: 1.0972 
Epoch 10/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1750 - loss: 1.1007     
Epoch 11/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0667 - loss: 1.1019     
Epoch 12/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accur

In [18]:
# MAKING PREDICTIONS

Y_Pred = model.predict(X)
Y_Pred_Classes = np.argmax(Y_Pred, axis=1)
Y_Classes = np.argmax(Y,axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


In [19]:
Y_Pred_Classes

array([1, 1, 1, 1, 0])

In [20]:
Y_Classes

array([0, 1, 2, 1, 0])

In [22]:
# CALCULATING ACCURACY
accuracy = accuracy_score(Y_Classes, Y_Pred_Classes)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 60.00%


In [13]:
"""
WHEN Y VARIABLE IS MULTICLASS , AND WHEN YOU APPLIED LABEL ENCODING ON IT ---> LOSS FUNCTION : SPARSE CATEGORICAL CROSS-ENTROPY
WHEN Y VARIABLE IS MULTICLASS , AND WHEN YOU APPLIED ONE HOT ENCODING ON IT ---> LOSS FUNCTION : CATEGORICAL CROSS-ENTROPY
"""

'\nWHEN Y VARIABLE IS MULTICLASS , AND WHEN YOU APPLIED LABEL ENCODING ON IT ---> LOSS FUNCTION : SPARSE CATEGORICAL CROSS-ENTROPY\nWHEN Y VARIABLE IS MULTICLASS , AND WHEN YOU APPLIED ONE HOT ENCODING ON IT ---> LOSS FUNCTION : CATEGORICAL CROSS-ENTROPY\n'

In [23]:
"""
Imagine a dataset where you have a "Fruit" column with values: "Apple", "Banana", "Cherry".

Fruit
-----
Apple
Banana
Cherry

Applying one-hot encoding:
-------------------------
Fruit_Apple	Fruit_Banana	Fruit_Cherry
1	0	0
0	1	0
0	0	1
"""

'\nImagine a dataset where you have a "Fruit" column with values: "Apple", "Banana", "Cherry".\n\nFruit\n-----\nApple\nBanana\nCherry\n\nApplying one-hot encoding:\n-------------------------\nFruit_Apple\tFruit_Banana\tFruit_Cherry\n1\t0\t0\n0\t1\t0\n0\t0\t1\n'